
# generates clightgen normalized v files as needed
CCode/%.v: CCode/%.c
	clightgen -normalize $<

# since we have double colon rules, we can extend the original file!
clean::
	@rm -f CCode/*.v CCode/*.glob CCode/*.vo CCode/*.vok CCode/*.vos


